services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iswara_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/public/build
      - /var/www/html/vendor
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - iswara_network

  frontend:
    image: node:20
    container_name: iswara_frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    networks:
      - iswara_network
  db:
    image: postgres:15
    container_name: iswara_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - iswara_db_data:/var/lib/postgresql/data
    networks:
      - iswara_network

networks:
  iswara_network:
    driver: bridge

volumes:
  iswara_db_data:
